project:
  type: website
  resources:
    - "*.jpg"
    - "*.png"

website:
  title: "Andrea Zonca"
  navbar:
    right:
      - about.qmd
      - consult.qmd
      - icon: github
        href: https://github.com/zonca
      - icon: twitter
        href: https://twitter.com/andreazonca
      - icon: mastodon
        href: https://mastodon.online/@zonca
format:
  html:
    theme: litera
    css: styles.css
    code-block-bg: E9ECEF

execute:
  freeze: auto  # re-render only when source changes
