project:
  type: website
  resources:
    - "*.jpg"
    - "*.png"

website:
  title: "Andrea Zonca"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zonca
      - icon: twitter
        href: https://twitter.com/andreazonca
format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto  # re-render only when source changes
